### ISSUE TITLE
Please upload weight file of the trained model 

### ISSUE THREAD

**Issue by VarunBelagali98** [anki-xyz/bagls#1]
Is it possible to upload a .h5 file of the trained Unet model ?

**Comment by anki-xyz** [comment]
Hi @VarunBelagali98, we will discuss this. Maybe we can deposit one on zenodo.

**Comment by anki-xyz** [comment]
Here is one trained U-Net from the [OpenHSV](https://www.nature.com/articles/s41598-021-93149-0) paper: https://github.com/anki-xyz/openhsv/tree/master/openhsv/cnn
